### ISSUE TITLE
Couldn't find section with name .text

### ISSUE THREAD

**Issue by EQuioMaX** [Lahvuun/sekirofpsunlock#5]
Ran release `sekirofpsunlock-v0.2.2` while the game was running (tried several times until the main menu was accessible) and got this error:
```
❯ sudo setcap CAP_SYS_PTRACE=+eip sekirofpsunlock

❯ ./sekirofpsunlock 60 set-fps 165
couldn't find section with name .text
find_section_info(".text", ...) failed
patch_game_fps() failed
main_fps() failed
handle_arguments() failed
patch() failed
```
The game runs perfectly fine, but at 60 fps.
I am not running the Steam copy of the game, could that be the issue?
Running this script while the game was running -- https://github.com/Lahvuun/sekirofpsunlock/blob/master/contrib/dumpsection.py -- gives the error:
```
❯ sudo ./test.py /proc/$(pgrep sekiro.exe)/mem .text > text 
Traceback (most recent call last):
  File "/home/user/Downloads/sfu/./test.py", line 57, in <module>
    raise ValueError("Could not find section {} in {}".format(section_name, mem_path))
ValueError: Could not find section .text in /proc/221759/mem

```
The PID matches what `top` reports for `sekiro.exe`.
Tried using Bottles version of wine (Caffe 7.7), wine-staging 7.13, and wine-tkg 7.5 all with the same error.
Esync and Fsync are enabled.
Also tried running through lutris, no change.
Specs: 
- ArchLinux - 5.18.13-lqx (Liquorix kernel)
- Ryzen 7 5800HS, 16GB RAM
- Nvidia RTX 3060 Max-Q (Driver -- 515.57)

**Comment by Lahvuun** [comment]
Interesting. It's certainly a windows executable — otherwise you'd be getting a different error. Either the code section is named differently (the game should still work, though I'm not a PE expert), or... there isn't one?

Let's start by examining your `sekiro.exe`. Upload it here.

**Comment by EQuioMaX** [comment]
[sekiro.tar.gz](https://github.com/Lahvuun/sekirofpsunlock/files/9176660/sekiro.tar.gz)
Github doesn't support uploading exe's so I have compressed it into a `tar.gz`.

**Comment by Lahvuun** [comment]
Your `.text` section is named `.textV`! A few others have `V` appended, too. Where'd you get this binary?

**Comment by Lahvuun** [comment]
You don't have to answer that, by the way.

Backup `sekiro.exe`, then run this:
`printf '\x00' | dd of=sekiro.exe bs=1 seek=693 count=1 conv=notrunc`
See if the game runs (it should), then see if it gets patched.

**Comment by EQuioMaX** [comment]
Patching `sekiro.exe` by following the comment above seems to be working, and I can see the fps crossing 70.
Running `sekirofpsunlock` didn't give any errors either.
Thank you very much for the help!

**Comment by Lahvuun** [comment]
Great!

I'll keep this issue open until I figure out a way to detect `.text` regardless of its name.
